//
//  Tokens.swift
//
//  The design vocabulary. Colour, type, spacing, radius, motion.
//
//  RULE: no view in this app contains a raw hex, a raw point size, or a magic
//  spacing number. If you need one that isn't here, add it here first.
//
//  docs/05-DESIGN-SYSTEM.md.
//

import SwiftUI

// MARK: - Colour
//
// Backed by the asset catalog (generated by scripts/make_colorsets.py), so every
// token gets light and dark variants for free.

extension Color {

    // Brand
    static let brandPrimary = Color("BrandPrimary")
    static let brandSecondary = Color("BrandSecondary")
    static let brandAccent = Color("BrandAccent")

    // Surfaces
    static let surfaceBase = Color("SurfaceBase")
    static let surfaceRaised = Color("SurfaceRaised")
    static let surfaceSunken = Color("SurfaceSunken")

    // Text
    static let textPrimary = Color("TextPrimary")
    static let textSecondary = Color("TextSecondary")
    static let separatorLine = Color("Separator")

    // Semantic
    static let success = Color("Success")
    static let caution = Color("Caution")
    static let critical = Color("Critical")

    /// Mid-grey exercise background. Theme-independent by design: a Gabor patch
    /// must be able to modulate symmetrically above and below the background
    /// luminance. On black you cannot render negative contrast at all, which is
    /// why the reference app's stimuli are psychophysically meaningless.
    static let stimulusNeutral = Color("StimulusNeutral")
}

// MARK: - Track identity

extension Track {
    var tint: Color {
        switch self {
        case .monocular: .brandPrimary
        case .dichoptic: .brandAccent
        case .game: .brandSecondary
        case .assessment: .textSecondary
        }
    }
}

extension EvidenceTier {
    var tint: Color {
        switch self {
        case .a: .success
        case .b: .brandPrimary
        case .c: .textSecondary
        }
    }
}

// MARK: - Spacing (4-pt grid)

enum Spacing {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 16
    static let lg: CGFloat = 24
    static let xl: CGFloat = 32
    static let xxl: CGFloat = 48
}

// MARK: - Radius

enum Radius {
    static let card: CGFloat = 20
    static let button: CGFloat = 14
    static let chip: CGFloat = 10
    static let sheet: CGFloat = 28
    /// Kids mode softens everything.
    static let cardKids: CGFloat = 24
}

// MARK: - Layout

enum Layout {
    /// Content never stretches wider than this on iPad — long measure is hard to
    /// read and makes a big screen feel like a stretched phone.
    static let maxContentWidth: CGFloat = 760

    /// Apple's minimum, and ours everywhere.
    static let minTouchTarget: CGFloat = 44
    /// Under-5 profiles get much bigger targets.
    static let minTouchTargetKids: CGFloat = 60

    static let buttonHeight: CGFloat = 50
    static let sidebarMin: CGFloat = 220
    static let sidebarIdeal: CGFloat = 260
    static let sidebarMax: CGFloat = 320
}

// MARK: - Typography
//
// System font throughout: free Dynamic Type, free localisation, zero bundle
// weight. SF Rounded only in kids mode.

enum TypeScale {
    static func displayLarge(rounded: Bool = false) -> Font {
        .system(size: 34, weight: .bold, design: rounded ? .rounded : .default)
    }
    static func title(rounded: Bool = false) -> Font {
        .system(size: 28, weight: .semibold, design: rounded ? .rounded : .default)
    }
    static func headline(rounded: Bool = false) -> Font {
        .system(size: 20, weight: .semibold, design: rounded ? .rounded : .default)
    }
    static func body(rounded: Bool = false) -> Font {
        .system(size: 17, weight: .regular, design: rounded ? .rounded : .default)
    }
    static func callout(rounded: Bool = false) -> Font {
        .system(size: 16, weight: .regular, design: rounded ? .rounded : .default)
    }
    static func caption(rounded: Bool = false) -> Font {
        .system(size: 13, weight: .regular, design: rounded ? .rounded : .default)
    }
    /// Monospaced digits so numbers don't jitter as they change.
    static func metric(rounded: Bool = false) -> Font {
        .system(size: 44, weight: .semibold, design: rounded ? .rounded : .default)
            .monospacedDigit()
    }
}

// MARK: - Motion
//
// Nothing bounces. Nothing flashes. The emotional job here is reassurance.

enum Motion {
    static let quick = Animation.easeOut(duration: 0.18)
    static let standard = Animation.easeInOut(duration: 0.25)
    static let gentle = Animation.easeInOut(duration: 0.4)

    /// Wraps an animation so it disappears entirely under Reduce Motion.
    static func respectful(_ animation: Animation, reduceMotion: Bool) -> Animation? {
        reduceMotion ? nil : animation
    }
}

// MARK: - Safety constants
//
// Not styling. These are enforced limits that happen to live near the UI.
// docs/01-RESEARCH-BRIEF.md section 7.

enum SafetyLimits {
    /// Hard ceiling on any stimulus temporal frequency. Photosensitive epilepsy
    /// is triggered by high-contrast oscillation in the 3-60 Hz band; we stay
    /// entirely below it. Enforced by FlickerGuard in Phase 5.
    static let maxTemporalRateHz: Double = 3.0

    /// 20-20-20: every 20 minutes, look 20 feet away for 20 seconds.
    static let breakIntervalSeconds: Int = 20 * 60
    static let breakDurationSeconds: Int = 20

    /// No session may exceed this, whatever the user asks for.
    static let maxSessionSeconds: Int = 30 * 60
}
